"""
Method 5 — MLP distilled from Q-learning.
Trained by supervised learning on samples generated by the Q-table.
Continuous inputs (no binning at inference).
"""

import numpy as np
from decision.base import DecisionMethod
from decision.q_learning import QLearning


def relu(x): return np.maximum(0, x)


class MLPDistilled(DecisionMethod):
    name = "MLP par distillation"
    description = "MLP trained by supervised distillation from a Q-learning oracle."
    learning_type = "hybrid (RL->supervised)"

    HIDDEN = 8

    def __init__(self):
        rng = np.random.default_rng(0)
        self.W1 = rng.normal(0, 0.3, (3, self.HIDDEN)).astype(np.float32)
        self.b1 = np.zeros(self.HIDDEN, dtype=np.float32)
        self.W2 = rng.normal(0, 0.3, (self.HIDDEN, 3)).astype(np.float32)
        self.b2 = np.zeros(3, dtype=np.float32)

    @staticmethod
    def _normalize(state):
        return np.array([
            state["theta"] / 50.0,
            (state["v_batt"] - 3.2) / 0.5,
            (state["v_sc"] - 2.5) / 0.5,
        ], dtype=np.float32)

    def _forward(self, x):
        h = relu(x @ self.W1 + self.b1)
        return h @ self.W2 + self.b2

    def decide(self, state):
        x = self._normalize(state)
        logits = self._forward(x)
        return int(np.argmax(logits))

    def memory_bytes(self):
        return 3*self.HIDDEN + self.HIDDEN + self.HIDDEN*3 + 3

    def train(self, env_factory):
        # 1) Train a Q-learning oracle
        oracle = QLearning()
        oracle.train(env_factory)

        # 2) Generate a supervised dataset
        rng = np.random.default_rng(1)
        N = 20000
        X = np.zeros((N, 3), dtype=np.float32)
        y = np.zeros(N, dtype=np.int32)
        for i in range(N):
            state = {
                "theta": rng.uniform(-40, 85),
                "v_batt": rng.uniform(2.8, 3.7),
                "v_sc": rng.uniform(1.8, 3.3),
                "packets_pending": 0,
            }
            action = oracle.decide(state)
            X[i] = self._normalize(state)
            y[i] = action

        # 3) Train MLP by gradient descent (cross-entropy)
        lr = 0.05
        EPOCHS = 80
        BATCH = 128

        def softmax(z):
            z = z - z.max(axis=1, keepdims=True)
            ez = np.exp(z)
            return ez / ez.sum(axis=1, keepdims=True)

        for epoch in range(EPOCHS):
            perm = rng.permutation(N)
            for i in range(0, N, BATCH):
                idx = perm[i:i+BATCH]
                xb, yb = X[idx], y[idx]
                h = relu(xb @ self.W1 + self.b1)
                logits = h @ self.W2 + self.b2
                p = softmax(logits)
                t = np.zeros_like(p)
                t[np.arange(len(yb)), yb] = 1.0
                dlogits = (p - t) / len(yb)
                dW2 = h.T @ dlogits
                db2 = dlogits.sum(axis=0)
                dh = dlogits @ self.W2.T
                dh[h <= 0] = 0
                dW1 = xb.T @ dh
                db1 = dh.sum(axis=0)
                self.W2 -= lr * dW2
                self.b2 -= lr * db2
                self.W1 -= lr * dW1
                self.b1 -= lr * db1
